nginx:
    image: yjw2288/nginx
    ports:
        - "80:80"
    links:
        - appa:app
        - appb:app2
#        - appc:app3

appa:
    image: yjw2288/app

appb:
    image: yjw2288/app

#full db connection, just launch 2 tomcat
#appc:
#    image: yjw2288/app
